eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: user
  profiles:
   active: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  activemq:
    enabled: false
    broker-url: tcp://127.0.0.1:61616
    password: jackson123
    username: jackson
  rabbitmq:
     enabled: true
     host: 192.168.221.254
     port: 5677
     username: pttl_mq_user
     password: isu#12934.@1235.0)#
     virtual-host: /sit
     exchange: transaction

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.pttl.entity.user