eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8768
spring:
  profiles:
   active: uat
  application:
    name: compensator
  datasource:
    product:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: 123456
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/product?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
    user:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: 123456
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
  redis:
        block-when-exhausted: true
        database: 1
        host: 192.168.242.128
        pool:
          max-active: 1024
          max-idle: 200
          max-wait: 10000
          min-idle: 0
        password: '123456'
        port: 6379
        timeout: 10000
  activemq:
    enabled: false
    broker-url: tcp://127.0.0.1:61616
    password: jackson123
    username: jackson
  rabbitmq:
     #host: 192.168.221.254
     host: 192.168.242.188
     port: 5677
     username: pttl_mq_user
     password: isu#12934.@1235.0)#
     virtual-host: /uat
     exchange: transaction
     publisher-confirms: true
     publisher-returns: true
     listener:
       simple:
         acknowledge-mode: manual 
         retry:
           enabled: true
           max-attempts: 2
           initial-interval: 1000			
dawdler:
  transaction:
    mqserver: rabbitmq