eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  profiles:
   active: uat
  application:
    name: order
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
        block-when-exhausted: true
        database: 1
        host: 192.168.242.128
        pool:
          max-active: 1024
          max-idle: 200
          max-wait: 10000
          min-idle: 0
        password: '123456'
        port: 6379
        timeout: 10000
  activemq:
    broker-url: tcp://127.0.0.1:61616
    password: jackson123
    username: jackson
  rabbitmq:
     #host: 192.168.221.254
     host: 192.168.242.188
     port: 5677
     username: pttl_mq_user
     password: isu#12934.@1235.0)#
     virtual-host: /uat
     exchange: transaction
     publisher-confirms: true
     publisher-returns: true
     listener:
       simple:
         acknowledge-mode: manual 
         retry:
           enabled: true
           max-attempts: 2
           initial-interval: 1000		
feign:
  hystrix:
    enabled: false //feign开启hystrix支持
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0  
  OkToRetryOnAllOperations: false 
dawdler:
  transaction:
    mqserver: rabbitmq
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.pttl.service.order.entity